### ISSUE TITLE
Add readOne method

### ISSUE THREAD

**Issue by richrd** [vettloffah/odoo-await#5]
I'm proposing to add a `readOne` method that's similar to `read` but only accepts a single ID and returns a single result or undefined. It'd be neater to use when just getting a single record without having to then do something like `record = records[0];`

Any thoughts?

**Comment by vettloffah** [comment]
Hi sorry I didn't see this before. A couple of notes here:

1. In version 2.0, you can supply a single ID or an array of ID's in the read method. (but it still returns an array)
2. It would be pretty easy to return a single record if a single ID is supplied, since it's already checking for an array.
3. There is a fairly elegant way to get the single record now, and it looks like this:

```js
const record = (await odoo.read('res.partner', 384, ['name','email]))[0]
```

I will add #2 above to the next release.

Thank you

**Comment by richrd** [comment]
Thanks! That workaround is indeed pretty much what I want. I had forgotten that accessing non-existing array indices in JavaScript just returns `undefined` anyway. So no need for an if statement. That said I think a `readOne` method is probably unnecessary.
